### ISSUE TITLE
esbundle

### ISSUE THREAD

**Issue by ChristopherHButler** [JonathanILevi/TreeSerial#1]
Hey, 
This is going to be a strange message and sorry for reaching out like this... (not sure how else I could contact you??) but is this the JonathanLevi who wrote esbundle on npm ?  It seems like the package is dead but I couldn't find it in your repo list. I was planning to build a project and that was the first name that came to mind so I was wondering if you are not maintaining the package if I could take it over?
Best regards, 
Chris

**Comment by JonathanILevi** [comment]
Yeah, that was me.  I don't think I ever made meaningful code, I was just figuring out npm, when I moved on from the idea.  I emailed you directly.
